[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 1000000
monitor_dtr = 0
monitor_rts = 0
board_upload.flash_size = 16MB
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.psram_type = qio
board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi 
build_flags =
    -O3
    -DCORE_DEBUG_LEVEL=0
    -ffast-math 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
lib_deps =
    tanakamasayuki/TensorFlowLite_ESP32 @ ^1.0.0
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.3
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4